### PR TITLE
Add myself as a maintainer

### PR DESCRIPTION
**Pull request by asmeurer**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by moorepants** [comment]
Not sure if I should merge with everything failing.

**Comment by asmeurer** [comment]
Can you add some kind of CI skip to the merge commit message

**Comment by asmeurer** [comment]
The code looks right in .travis.yml. Maybe just push an empty commit up?

**Comment by asmeurer** [comment]
Maybe it has to do with the skip ci in the commit message? I'm very confused what is happening here.

**Pull request merged**
